{% set name = "gstlal-burst" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 53409b0fa11e19c22602b0f0fd09909a783a7cbf60c1d98bf4421f460215f9bd
  patches:
    # https://git.ligo.org/lscsoft/gstlal/issues/46
    - missing-links.patch
    # https://git.ligo.org/lscsoft/gstlal/issues/47
    - gstaudio.patch
    # https://git.ligo.org/lscsoft/gstlal/issues/48
    - unused-import-triggergen.patch

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    # header is included, but never used, reported upstream
    - lalburst
    - lalinspiral
  number: 0
  skip: true  # [win or py>36]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - pkg-config >=0.18.0  # [unix]
  host:
    - libglib
    - gobject-introspection >=1.30.0
    - gsl
    - gst-plugins-base
    - gstlal >=1.6.0
    - gstreamer
    - liblal >=6.20.1
    - liblalburst >=1.5.2
    - liblalinspiral
    - numpy
    - python
  run:
    - glib
    - gobject-introspection >=1.30.0
    - gsl
    - gst-plugins-base
    - gst-python
    - gstlal >=1.6.0
    - gstlal-ugly >=1.7.0
    - gstreamer
    - h5py
    - liblal >=6.20.1
    - ligo-scald
    - ligo-segments >=1.2.0
    - lscsoft-glue >=2.0.0
    - {{ pin_compatible('numpy') }}
    - python
    - python-confluent-kafka >=0.11.4
    - scipy

test:
  imports:
    - gstlal.snax
    - gstlal.snax.auxcache
    - gstlal.snax.feature_extractor
    - gstlal.snax.multichannel_datasource
    - gstlal.snax.multirate_datasource
    - gstlal.snax.sngltriggertable
    - gstlal.snax.utils
    - gstlal.snax.waveforms
    - gstlal.snglbursttable
    - gstlal.streamburca
  requires:
    - pkg-config  # [unix]
  commands:
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")  # [not win]
    # check executables
    - gstlal_cs_triggergen --help
    - gstlal_snax_aggregate --help
    - gstlal_snax_bank_overlap --help
    - gstlal_snax_combine --help
    - gstlal_snax_dag_offline --help
    - gstlal_snax_dag_online --help
    - gstlal_snax_extract --help
    - gstlal_snax_monitor --help
    - gstlal_snax_sink --help
    - gstlal_snax_synchronize --help
    - gstlal_snax_whiten --help
    # check pkg-config
    - pkg-config --print-errors --libs gstlal-burst  # [unix]

about:
  home: "https://lscsoft.docs.ligo.org/gstlal/"
  dev_url: "https://git.ligo.org/lscsoft/gstlal/"
  doc_url: "https://lscsoft.docs.ligo.org/gstlal/"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "GStreamer for generic transient data analysis"
  description: |
    This package contains the plugins and shared libraries required
    to run the gstlal burst (generic transient) pipeline.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
