{% set name = "gstlal-burst" %}
{% set version = "0.5.0" %}

# dependencies
{% set gobject_introspection_version = "1.30.0" %}
{% set gstlal_version = "1.10.0" %}
{% set gstlal_ugly_version = "1.10.0" %}
{% set lal_version = "7.2.4" %}
{% set lalburst_version = "1.7.0" %}
{% set lalmetaio_version = "3.0.2" %}
{% set lalsimulation_version = "4.0.2" %}
{% set ligo_scald_version = "0.8.1" %}
{% set ligo_segments_version = "1.2.0" %}
{% set python_ligo_lw_version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: a62deaf8f30651b68429c28327bf7e72bb76b462b7810d580c57c96d0b94e453
  patches:
    - py-compile-imp.patch
    # backport https://git.ligo.org/lscsoft/gstlal/-/merge_requests/611
    - pyobject_head_init.patch
    - no-link-libpython.patch  # [osx]

build:
  error_overlinking: true
  ignore_run_exports:
    # needed by configure, but not used
    - liblalburst
    - liblalmetaio
    # not linked, but needed at runtime
    - gobject-introspection
    - gst-python
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make  # [unix]
    - pkg-config >=0.18.0  # [unix]
  host:
    - gobject-introspection >={{ gobject_introspection_version }}
    - gsl
    - gst-plugins-base
    - gstlal >={{ gstlal_version }}
    - gstreamer
    - libglib
    - liblal >={{ lal_version }}
    - liblalburst >={{ lalburst_version }}
    - liblalmetaio
    - python
  run:
    - gobject-introspection >={{ gobject_introspection_version }}
    - gst-python
    - gstlal >={{ gstlal_version }}
    - gstlal-inspiral
    - gstlal-ugly >={{ gstlal_ugly_version }}
    - ligo-segments >={{ ligo_segments_version }}
    - matplotlib-base
    - numpy
    - python
    - python-lalburst >={{ lalburst_version }}
    - scipy

test:
  requires:
    - pkg-config  # [unix]
  imports:
    - gstlal.snglbursttable
    - gstlal.streamburca
  commands:
    - export GSTLAL_FIR_WHITEN=0  # [unix]
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")  # [unix]
    # check executables
    - gstlal_cherenkov_burst --help
    - gstlal_cherenkov_calc_likelihood --help
    - gstlal_cherenkov_calc_rank_pdfs --help
    - gstlal_cherenkov_inj --help
    - gstlal_cherenkov_plot_rankingstat --help
    - gstlal_cherenkov_plot_summary --help
    - gstlal_cherenkov_zl_rank_pdfs --help
    - gstlal_cs_triggergen --help
    - gstlal_impulse_inj --help
    # check pkg-config
    - pkg-config --print-errors --libs gstlal-burst  # [unix]

about:
  home: https://lscsoft.docs.ligo.org/gstlal/
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://lscsoft.docs.ligo.org/gstlal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GStreamer for generic transient data analysis
  description: |
    This package contains the plugins and shared libraries required
    to run the gstlal burst (generic transient) pipeline.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
