{% set name = "gstlal-burst" %}
{% set version = "0.4.0" %}

# dependencies
{% set gobject_introspection_version = "1.30.0" %}
{% set gstlal_version = "1.9.0" %}
{% set gstlal_ugly_version = "1.9.1" %}
{% set lal_version = "6.20.1" %}
{% set lalburst_version = "1.5.2" %}
{% set lalmetaio_version = "1.5.1" %}
{% set lalsimulation_version = "1.8.0" %}
{% set ligo_scald_version = "0.7.2" %}
{% set ligo_segments_version = "1.2.0" %}
{% set lscsoft_glue_version = "2.0.0" %}
{% set python_ligo_lw_version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: f9c68aac21638bb180b3583b90f94505da0b7adeed7eaa6b9377b0129594fd95
  patches:
    - no-link-libpython.patch  # [osx]

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    # needed by configure, but not used
    - liblalburst
    - liblalmetaio
    # not linked, but needed at runtime
    - gobject-introspection
    - gst-python
    - numpy
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - pkg-config >=0.18.0  # [unix]
  host:
    - gobject-introspection >={{ gobject_introspection_version }}
    - gsl
    - gst-plugins-base
    - gstlal >={{ gstlal_version }}
    - gstreamer
    - libglib
    - liblal >={{ lal_version }}
    - liblalburst >={{ lalburst_version }}
    - liblalmetaio
    - numpy
    - python
  run:
    - gobject-introspection >={{ gobject_introspection_version }}
    - gsl
    - gst-plugins-base
    - gst-python
    - gstlal >={{ gstlal_version }}
    - gstlal-ugly >={{ gstlal_ugly_version }}
    - gstreamer
    - h5py
    - libglib
    - liblal >={{ lal_version }}
    - ligo-scald >={{ ligo_scald_version }},<0.8.0a0
    - ligo-segments >={{ ligo_segments_version }}
    - lscsoft-glue >={{ lscsoft_glue_version }}
    - matplotlib-base <3.6.0a0
    - {{ pin_compatible('numpy') }}
    - python
    - python-confluent-kafka >=0.11.4
    - python-lalburst >={{ lalburst_version }}
    - scipy

test:
  imports:
    - gstlal.snax
    - gstlal.snax.auxcache
    - gstlal.snax.feature_extractor
    - gstlal.snax.multichannel_datasource
    - gstlal.snax.pipeparts
    - gstlal.snax.sngltriggertable
    - gstlal.snax.utils
    - gstlal.snax.waveforms
    - gstlal.snglbursttable
    - gstlal.streamburca
  requires:
    - pkg-config  # [unix]
  commands:
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")  # [not win]
    # check executables
    - gstlal_cs_triggergen --help
    - gstlal_snax_aggregate --help
    - gstlal_snax_bank_overlap --help
    - gstlal_snax_combine --help
    - gstlal_snax_dag_offline --help
    - gstlal_snax_dag_online --help
    - gstlal_snax_extract --help
    - gstlal_snax_monitor --help
    - gstlal_snax_sink --help
    - gstlal_snax_synchronize --help
    - gstlal_snax_whiten --help
    # check pkg-config
    - pkg-config --print-errors --libs gstlal-burst  # [unix]

about:
  home: https://lscsoft.docs.ligo.org/gstlal/
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://lscsoft.docs.ligo.org/gstlal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GStreamer for generic transient data analysis
  description: |
    This package contains the plugins and shared libraries required
    to run the gstlal burst (generic transient) pipeline.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
